export default {
  // Admin
  getAdmin: 'GET_ADMIN',
  // Overlays
  addOverlay: 'ADD_OVERLAY',
  closeOverlay: 'CLOSE_OVERLAY',
  // Colors
  updateColor: 'UPDATE_COLOR',
  addColor: 'ADD_COLOR',
  removeColor: 'REMOVE_COLOR',
  // Display
  changeDisplay: 'CHANGE_DISPLAY',
  // Fonts
  changeFontsPreviewText: 'CHANGE_FONTS_PREVIEW_TEXT',
  changeFontsPreviewLayout: 'CHANGE_FONTS_PREVIEW_LAYOUT',
  changeFontInput: 'CHANGE_FONT_INPUT',
  loadFonts: 'LOAD_FONTS',
  saveFonts: 'SAVE_FONTS',
  submitCustomFont: 'SUBMIT_CUSTOM_FONT',
  removeCustomFont: 'REMOVE_CUSTOM_FONT',
  customFontIncluded: 'CUSTOM_FONT_INCLUDED',
  // Media
  addMedia: 'ADD_MEDIA',
  removeMedia: 'REMOVE_MEDIA',
  getMediaItem: 'GET_MEDIA_ITEM',
  // Menu
  updateMenu: 'UPDATE_MENU',
  addMenu: 'ADD_MENU',
  changeMenuFields: 'CHANGE_FIELDS',
  changeMenuToDefault: 'CHANGE_TO_DEFAULT',
  validateMenuSlug: 'VALIDATE_MENU_SLUG',
  // Menus
  removeMenu: 'REMOVE_MENU',
  duplicateMenu: 'DUPLICATE_MENU',
  // Page
  getPage: 'GET_PAGE',
  updatePage: 'UPDATE_PAGE',
  addPage: 'ADD_PAGE',
  changePageFields: 'CHANGE_FIELDS',
  changePageToDefault: 'CHANGE_TO_DEFAULT',
  validatePageSlug: 'VALIDATE_PAGE_SLUG',
  restorePage: 'RESTORE_PAGE',
  // Pages
  removePage: 'REMOVE_PAGE',
  duplicatePage: 'DUPLICATE_PAGE',
  // Schemas
  removeSchema: 'REMOVE_SCHEMA',
  // Settings
  changeSettingValue: 'CHANGE_SETTING_VALUE',
  saveSettings: 'SAVE_SETTINGS',
  // Users
  removeUser: 'REMOVE_USER',
  addUser: 'ADD_USER',
  // DND
  startDragging: 'START_DRAGGING',
  onDroppable: 'ON_DROPPABLE',
  outDroppable: 'OUT_DROPPABLE',
  stopDragging: 'STOP_DRAGGING',
  // Page builder
  pbSetMenuOpened: 'PB_SET_MENU_OPENED',
  pbSetMenuSide: 'PB_SET_MENU_SIDE',
  pbSetMenuTab: 'PB_SET_MENU_TAB',
  pbSetGeneralElementsMenuSearch: 'PB_SET_GENERAL_ELEMENTS_MENU_SEARCH',
  pbSetGeneralElementsMenuOpened: 'PB_SET_GENERAL_ELEMENTS_MENU_OPENED',
  pbOpenElementsMenu: 'PB_OPEN_ELEMENTS_MENU',
  pbCloseElementsMenu: 'PB_CLOSE_ELEMENTS_MENU',
  pbToggleCategory: 'PB_TOGGLE_CATEGORY',
  pbOverElement: 'PB_OVER_ELEMENT',
  pbOutElement: 'PB_OUT_ELEMENT',
  pbSelectElement: 'PB_SELECT_ELEMENT',
  pbDoAction: 'PB_DO_ACTION',
  pbUndoAction: 'PB_UNDO_ACTION',
  pbRedoAction: 'PB_REDO_ACTION',
  // Tabs
  removeTab: 'REMOVE_TAB',
  // styles
  saveStyle: 'SAVE_STYLE',
  changeStyleProp: 'CHANGE_STYLE_PROP'
};
