version: '2'
services:
  nginx:
    build: ./nginx
  relax:
    build: ../
    volumes:
      - relax-media:/app/public/media
  mongo:
    image: mongo
    volumes:
      - relax-mongo:/data/db

volumes:
  relax-media:
    external:
      name: relax-media
  relax-mongo:
    external:
      name: relax-mongo
