export default {
  // Admin
  getAdmin: 'GET_ADMIN',
  // Colors
  updateColor: 'UPDATE_COLOR',
  addColor: 'ADD_COLOR',
  removeColor: 'REMOVE_COLOR',
  // Displays
  changeDisplay: 'CHANGE_DISPLAY',
  // Menu
  updateMenu: 'UPDATE_MENU',
  addMenu: 'ADD_MENU',
  changeMenuFields: 'CHANGE_FIELDS',
  changeMenuToDefault: 'CHANGE_TO_DEFAULT',
  // Menus
  removeMenu: 'REMOVE_MENU',
  duplicateMenu: 'DUPLICATE_MENU',
  // Page
  getPage: 'GET_PAGE',
  updatePage: 'UPDATE_PAGE',
  addPage: 'ADD_PAGE',
  changePageFields: 'CHANGE_FIELDS',
  changePageToDefault: 'CHANGE_TO_DEFAULT',
  validatePageSlug: 'VALIDATE_PAGE_SLUG',
  // Pages
  removePage: 'REMOVE_PAGE',
  duplicatePage: 'DUPLICATE_PAGE',
  // Settings
  changeSettingValue: 'CHANGE_SETTING_VALUE',
  saveSettings: 'SAVE_SETTINGS',
  // Users
  removeUser: 'REMOVE_USER',
  addUser: 'ADD_USER'
};
